name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up CouchDB
      id: couchdb
      uses: "cobot/couchdb-action@master"
      with:
        couchdb version: '2.3.1'
    - name: Run test
      run: |
        curl -sS -f http://${{steps.couchdb.outputs.ip}}:5984/
        curl -sS -f http://${{steps.couchdb.outputs.ip}}:5984/_users
