name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up CouchDB
      uses: ./.github/actions/couchdb-action
      with:
        couchdb version: '2.3.1'
    - name: wait for couchdb to come up
      run: sleep 10
    - name: Run test
      run: curl -f http://127.0.0.1:5984/_users
